### ISSUE TITLE
Filler Starts But Won't Process Blocks

### ISSUE THREAD

**Issue by CryptoBloks** [pinknetworkx/eosio-contract-api#54]
Followed the install directions located at https://github.com/pinknetworkx/eosio-contract-api

Server starts, populates database tables, maintains connection to the database and redis servers, but never attempts to connect to blockchain API or SHIP nodes.  Port 9001 is open and listing for connections, but no log files are written to error.log file in the logs directory (or anywhere else).

Unclear how to troubleshoot or force log output.  Any assistance would be greatly appreciated.

**Comment by CryptoBloks** [comment]
Unfortunately no log files are being written.  The only errors I can generate are at the console when running "yarn test" (as "yarn dev::test" mentioned in the docs does not exist).  That command generates the following output with some errors in the middle of the test, before it aborts:

 ```
root@atomic1:/opt/eosio-contract-api# yarn test
yarn run v1.22.18
$ mocha -r ts-node/register 'src/**/*.test.ts'


  Account handler
    getAccountAction
      ✔ gets a specific account stats, asset count, collections filter by owner and contract
    getAccountCollectionAction
      ✔ retrieves template and schema count from the given account and collection name
    getAccountsAction
      ✔ asset count by owner of the current contract
      when filter match argument is given
        1) returns asset count filtered by owner
      when filter collection name is given
        ✔ returns asset count filtered by collection name
      when filter schema name is given
        ✔ returns asset count filtered by schema name
      when filter template id is given
        ✔ returns asset count filtered by schema name

  AtomicAssets Assets API
    getRawAssetsAction V1
      ✔ works without filters
      ✔ filters by authorized collection account
      ✔ filters by hiding template accounts
      ✔ filters by duplicate templates for the same owner
      ✔ filters by having backed tokens
      ✔ filters by not having backed tokens
      ✔ filters by excluding offers
      ✔ filters by template mint
      ✔ filters by minimum template mint
      ✔ filters by minimum template mint (treating no template as 1)
      ✔ filters by maximum template mint
      ✔ filters by template blacklist
      ✔ filters by template whitelist
      ✔ filters by asset_id
      ✔ filters by owner
      ✔ filters by template
      ✔ filters by not having a template
      ✔ filters by collection name
      ✔ filters by schema name
      ✔ filters by being burned
      ✔ filters by not being burned
      ✔ filters by being transferable
      ✔ filters by not being transferable
      ✔ filters by being burnable
      ✔ filters by not being burnable
      ✔ filters by collection blacklist
      ✔ filters by collection whitelist
      ✔ filters by text data
      ✔ filters by number template_data
      ✔ filters by bool mutable_data
      ✔ filters by untyped immutable_data
      ✔ filters by match_immutable_name
      ✔ filters by match_mutable_name
      ✔ filters by match (template name)
      ✔ returns count
      ✔ orders ascending
      ✔ orders descending
      ✔ orders by asset_id
      ✔ orders by updated time
      ✔ orders by transferred time
      ✔ orders by minted
      ✔ orders by template_mint
      ✔ orders by name
      ✔ paginates
      ✔ filters by id (asset_id)
      ✔ filters by id range (asset_id)
      ✔ filters by date range

  getAccountsAction limits
    ✔ asset count by owner of the current contract, limited to 2
    ✔ limit bigger than set max
    ✔ set max smaller than default

  AtomicMarket Assets API
    getMarketAssetsAction V1
      ✔ orders by suggested median price (53ms)
      ✔ orders by suggested average price (38ms)
      ✔ orders by median price
      ✔ orders by average price

  auction handler
    getAuctions
      ✔ returns empty on no auctions
      ✔ returns all auctions without filters
      with template_blacklist args
        ✔ filter out auctions the given template matching the blacklist

  AtomicMarket Sales API
    getSalesAction V1
      ✔ works without filters
      ✔ filters by waiting state
      ✔ filters by listed state
      ✔ filters by canceled state
      ✔ filters by sold state
      ✔ filters by invalid state
      ✔ filters by multiple states
      ✔ filters by minimum asset count
      ✔ filters by maximum asset count
      ✔ filters by settlement symbol
      ✔ throws error when maximum price filter is set without settlement symbol
      ✔ filters by minimum price
      ✔ filters by maximum price
      ✔ filters out seller contracts unless whitelisted
      ✔ filters by blacklisted sellers
      ✔ filters by blacklisted buyers
      ✔ filters by accounts
      ✔ filters by seller
      ✔ filters by buyer
      ✔ filters by maker marketplace
      ✔ filters by taker marketplace
      ✔ filters by maker or taker marketplace
      ✔ filters by collection
      ✔ filters by minimum and maximum template mint
      ✔ filters by asset_id
      ✔ filters by asset owner
      ✔ filters by asset burned
      ✔ filters by asset not burned
      ✔ filters by asset template
      ✔ filters by not having an asset template
      ✔ filters by schema
      ✔ filters by asset being transferable
      ✔ filters by asset not being transferable
      ✔ filters by asset being burnable
      ✔ filters by asset not being burnable
      ✔ filters by text data
      ✔ filters by number template_data
      ✔ filters by bool mutable_data
      ✔ filters by untyped immutable_data
      ✔ filters by match_immutable_name
      ✔ filters by match_mutable_name
      ✔ filters by match (template name)
      ✔ filters by collection_whitelist
      ✔ filters by collection_blacklist
      ✔ filters by id (sale_id)
      ✔ filters by id range (sale_id)
      ✔ filters by date range
      ✔ returns count
      ✔ orders ascending
      ✔ orders descending
      ✔ orders by sale_id
      ✔ orders by created
      ✔ orders by updated
      ✔ orders by price
      ✔ orders by template_mint
      ✔ paginates
      ✔ formats and fills result
      with template_blacklist args
        ✔ filter out the given template matching the blacklist

  AtomicMarket Sales API
    getSalesAction V2
      ✔ works without filters (43ms)
      ✔ filters by waiting state
      ✔ filters by listed state
      ✔ filters by listed state (excluding sales that were unlisted)
      ✔ filters by sold state
      ✔ filters by invalid state
      ✔ filters by multiple states
      ✔ filters by minimum asset count
      ✔ filters by maximum asset count
      ✔ filters by settlement symbol
      ✔ throws error when minimum price filter is set without settlement symbol
      ✔ throws error when maximum price filter is set without settlement symbol
      ✔ filters by minimum price
      ✔ filters by maximum price
      ✔ filters out seller contracts unless whitelisted
      ✔ filters by blacklisted sellers
      ✔ filters by blacklisted buyers
      ✔ filters by accounts
      ✔ filters by single seller
      ✔ filters by sellers
      ✔ filters by single buyer
      ✔ filters by buyers
      ✔ filters by maker marketplace
      ✔ filters by taker marketplace
      ✔ filters by maker or taker marketplace
      ✔ filters by single collection
      ✔ filters by collections
      ✔ filters by minimum and maximum template mint
      ✔ filters by minimum template mint (excludes empty mints)
      ✔ filters by asset_id
      ✔ filters by asset owners
      ✔ filters by single asset owner
      ✔ filters by asset burned
      ✔ filters by asset not burned
      ✔ filters by asset templates
      ✔ filters by single asset template
      ✔ filters by not having an asset template
      ✔ filters by single schema
      ✔ filters by schemas
      ✔ filters by asset being transferable
      ✔ filters by asset not being transferable
      ✔ filters by asset being burnable
      ✔ filters by asset not being burnable
      ✔ filters by text data
      ✔ filters by number template_data
      ✔ filters by bool mutable_data
      ✔ filters by untyped immutable_data
      ✔ filters by data.name
      ✔ filters by search (template name filter)
      ✔ filters by match_immutable_name
      ✔ filters by match_mutable_name
      ✔ filters by match (template name)
      ✔ filters by collection_whitelist
      ✔ filters by collection_blacklist
      ✔ filters by id (sale_id)
      ✔ filters by id range (sale_id)
      ✔ filters by date range
      ✔ returns count
      ✔ orders ascending
      ✔ orders descending
      ✔ orders by sale_id
      ✔ orders by created
      ✔ orders by updated
      ✔ orders by price
      ✔ orders by template_mint
      ✔ paginates
      ✔ formats and fills result
      with template_blacklist arg
        ✔ filters out the sales that contains the template id

  filterQueryArgs
    ✔ removes values that are not defined in the filter
    ✔ returns the default value when the value is null
    ✔ returns the default value when the value is undefined
    ✔ returns the default value for arrays when the value is an empty string
    ✔ returns an empty array for arrays when the value is an empty string
    ✔ returns an empty array for arrays when the value is not set
    ✔ throws error when value is not in allowedValues
    ✔ throws error when array value is not in allowedValues
    ✔ throws error when array value is not valid
    ✔ allows valid valid values that are in allowedValues
    int type
      ✔ allows valid int values
      ✔ allows valid array int values
      ✔ throws errors for invalid int values
      ✔ throws error when int values are out of bounds
    string type
      ✔ allows valid string values
      ✔ allows valid array string values
      ✔ throws error when string values are out of bounds
    string type
      ✔ allows valid float values
      ✔ allows valid array float values
      ✔ throws errors for invalid float values
      ✔ throws error when float values are out of bounds
    bool type
      ✔ allows valid bool values
      ✔ allows valid array bool values
      ✔ throws errors for invalid bool values
    name type
      ✔ allows valid name values
      ✔ allows valid array name values
      ✔ throws errors for invalid name values

  utils
    ApplyActionGreyListFilters
      ✔ does not apply any filter if no filter is given
      ✔ applies white list filter, ignores given actions
      ✔ applies blacklist filter removing not allowed actions
      ✔ applies both white and black list filters on the actions
    extractNotificationIdentifiers
      ✔ extracts the notifications of type delta given key
      ✔ extracts the notifications of type trace given key
      ✔ ignores trace notification when no trace information is present
      ✔ ignores repeated identifiers
    respondApiError
2022-03-23T23:58:02.832Z [PID:25160] [warn] : Error occured while processing request Unhandled error {"stack":"Error: Unhandled error\n    at Context.<anonymous> (/opt/eosio-contract-api/src/api/utils.test.ts:112:50)\n    at callFn (/opt/eosio-contract-api/node_modules/mocha/lib/runnable.js:366:21)\n    at Test.Runnable.run (/opt/eosio-contract-api/node_modules/mocha/lib/runnable.js:354:5)\n    at Runner.runTest (/opt/eosio-contract-api/node_modules/mocha/lib/runner.js:678:10)\n    at /opt/eosio-contract-api/node_modules/mocha/lib/runner.js:801:12\n    at next (/opt/eosio-contract-api/node_modules/mocha/lib/runner.js:593:14)\n    at /opt/eosio-contract-api/node_modules/mocha/lib/runner.js:603:7\n    at next (/opt/eosio-contract-api/node_modules/mocha/lib/runner.js:486:14)\n    at Immediate._onImmediate (/opt/eosio-contract-api/node_modules/mocha/lib/runner.js:571:5)\n    at processImmediate (node:internal/timers:466:21)"}
      ✔ on unhandled error, formats to internal server error
      ✔ on api error handled error, shows the message and the code of the error
2022-03-23T23:58:02.834Z [PID:25160] [warn] : Error occured while processing request duplicated transaction {"code":409,"name":"Duplicated","showMessage":false,"stack":"stack"}
      ✔ on api error handled error, skip on sensitive information

  database tests
    ✔ Contract DB Transaction Insert (40ms)
    ✔ Contract DB Transaction Replace
    ✔ Contract DB Transaction Update
    ✔ Contract DB Transaction Delete
2022-03-23T23:58:02.897Z [PID:25160] [info] : Rollback 6 operations until block #1 
    ✔ Contract DB Rollback

  JobQueue
    ✔ queues job for immediate execution
    ✔ does not run 2 jobs with the same priority at the same time
    ✔ does run medium and low priority jobs at the same time
    ✔ does run a high and an other priority jobs at the same time
    ✔ only runs jobs that are due
    ✔ does not crash when no job is available
    ✔ emits error and queues the job again when the job function throws an error
    ✔ emits debug messages when a job starts and ends

  utils
    encodeDatabaseJson
      ✔ replaces NULL(\u0000) characters for blank space

  binary utility
    ✔ uint serialization
    ✔ eosio name serialization


  243 passing (4s)
  1 failing

  1) Account handler
       getAccountsAction
         when filter match argument is given
           returns asset count filtered by owner:

      AssertionError: expected 0 to equal 1
      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (src/api/namespaces/atomicassets/handlers/accounts.test.ts:174:44)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async runTxTest (src/utils/test.ts:64:20)
      at async Context.<anonymous> (src/utils/test.ts:72:20)



2022-03-23T23:58:03.015Z [PID:25160] [info] : Process stopping - cleaning up transactions... 
2022-03-23T23:58:03.015Z [PID:25160] [info] : All transactions aborted 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@atomic1:/opt/eosio-contract-api# 
```
The server does seem to make a connection to redis, though it doesn't appear to write anything based on the redis logs.  It connects and is able to write to the database as it creates a test db when running "yarn dev:init-test-db", and it creates a schema in the empty DB listed in the connections.config.json file.  As far as I can see, it makes no attempts to connect to the API or SHIP endpoints on the API node.

**Comment by CryptoBloks** [comment]
Additionally, I can get repeatable but different errors to fire, depending on wether or not I start the filler app prior to running the "yarn dev:init-test-db" and "yarn test" commands.  I'm unclear if these commands need to be run before or after the server is started, based on how they are included in the docs.

**Comment by fabian-emilius** [comment]
Filler will log to stdout by default so please only start the filler and check the logs. Doublecheck connection details that you can connect to the endpoints from your application
