### ISSUE TITLE
error on wax test network block 5713181

### ISSUE THREAD

**Issue by blokcrafter-dan** [pinknetworkx/eosio-contract-api#57]
I'm getting this in the logs and the filler stops processing blocks:

2022-04-01T14:11:03.685Z [PID:39] [error] : Error while processing data {"0":{"block_num":5713181,"block_id":"00572D1D5F287031296670F05D98B0BF5E74D858AAD890D8FAEB0CBCB201B86C","timestamp":"2020-01-08T14:06:54.500","producer":"blokcrafters","confirmed":0,"previous":"00572D1CBD84C4A07F9C5E08BC01D3642EF580A2717F063BF6AE22B7621C139F","transaction_mroot":"F55EAF60235FF5C72DF75DE13B392C1615C5A40D0356E01040283FD890AE1AA1","action_mroot":"4AD99641CEE022FC20B69EAD2E7ADAA575BBEAAB91812E7F5554F60C2307202F","schedule_version":44,"new_producers":null,"header_extensions":[],"producer_signature":"SIG_K1_KVa4tGBeT1Qxr7PEtje55iV7FTzZdtAHoA281Yi6oQ5GU9aVRkVUXp33AzACGTHCcr7Z9isNHaKJxLKzHwLaYmJ2ABKWzQ","transactions":[{"status":0,"cpu_usage_us":100,"net_usage_words":12,"trx":["packed_transaction",{"signatures":["SIG_K1_KfYkkbAHuos45XnM22RKU4k3UkyT9EZjc5oGbTFAc17gqzeSUsGCRVXfZK3ue1veqHdhw7mYz5fzBy3R33EQ3YAJnmbmpW"],"compression":0,"packed_context_free_data":{},"packed_trx":{"0":26,"1":226,"2":21,"3":94,"4":24,"5":45,"6":45,"7":139,"8":12,"9":243,"10":0,"11":0,"12":0,"13":0,"14":1,"15":128,"16":179,"17":194,"18":216,"19":32,"20":39,"21":105,"22":54,"23":0,"24":0,"25":0,"26":0,"27":0,"28":144,"29":221,"30":116,"31":1,"32":128,"33":179,"34":194,"35":216,"36":32,"37":39,"38":105,"39":54,"40":0,"41":0,"42":0,"43":0,"44":168,"45":237,"46":50,"47":50,"48":0,"49":0}}]}],"block_extensions":[],"last_irreversible":{"block_num":145901327,"block_id":"08B2470FDDEAB24C57E6801CF01252050220992EDFDE62B64A77A9FE722849AE"},"head":{"block_num":145901659,"block_id":"08B2485BDB246A0AF4223F855AEB010103B1177D5E4DDE7A047D4D24723FF077"}},"1":{"code":"atomicassets","scope":"atomicassets","table":"config","primary_key":"4982871454518345728","payer":"atomicassets","value":{"asset_counter":"1099511627780","offer_counter":"0","collection_format":[]},"present":true}}
2022-04-01T14:11:03.686Z [PID:39] [error] : Error occurred while executing block range from #5713172 to 5713181 
2022-04-01T14:11:03.686Z [PID:39] [error] : Consumer queue stopped due to an error at #5713181 Cannot read properties of undefined (reading 'length') {"stack":"TypeError: Cannot read properties of undefined (reading 'length')\n    at Object.callback (/home/application/app/build/filler/handlers/atomicassets/processors/config.js:12:82)\n    at DataProcessor.executeHeadQueue (/home/application/app/build/filler/processor.js:236:36)\n    at StateReceiver.process (/home/application/app/build/filler/receiver.js:154:38)\n    at async /home/application/app/build/filler/receiver.js:90:17\n    at async run (/home/application/app/node_modules/p-queue/dist/index.js:163:29)"}

**Comment by blokcrafter-dan** [comment]
This was an OE type error with me starting at the wrong block number for WAX Testnet.
The correct starting block number for WAX Testnet is 35795440

**Comment by Dewald928** [comment]
How can I get the correct block to start at on TLOS?
