### ISSUE TITLE
Telos testnet not syncing

### ISSUE THREAD

**Issue by Dewald928** [pinknetworkx/eosio-contract-api#66]
I was busy syncing the Telos testnet from block 104880000, but then it stopped halfway through with the following error.

```
eosio-contract-api-filler      | 2022-05-20T04:51:20.930Z [PID:39] [info] : Launching deserialization worker... 
eosio-contract-api-filler      | 2022-05-20T04:51:21.242Z [PID:39] [warn] : Could not find ABI for atomicmarket in cache, so requesting it... 
eosio-contract-api-filler      | 2022-05-20T04:51:22.459Z [PID:39] [warn] : Could not find ABI for atomicassets in cache, so requesting it... 
eosio-contract-api-postgres    | 2022-05-20 04:51:23.852 UTC [35] ERROR:  insert or update on table "atomicmarket_auctions" violates foreign key constraint "atomicmarket_auctions_maker_marketplace_fkey"
eosio-contract-api-postgres    | 2022-05-20 04:51:23.852 UTC [35] DETAIL:  Key (market_contract, maker_marketplace)=(atomicmarket, ) is not present in table "atomicmarket_marketplaces".
eosio-contract-api-postgres    | 2022-05-20 04:51:23.852 UTC [35] STATEMENT:  COMMIT
eosio-contract-api-filler      | 2022-05-20T04:51:23.853Z [PID:39] [error] : Failed to execute SQL query  {"queryText":"COMMIT","values":[],"error":{"length":386,"name":"error","severity":"ERROR","code":"23503","detail":"Key (market_contract, maker_marketplace)=(atomicmarket, ) is not present in table \"atomicmarket_marketplaces\".","schema":"public","table":"atomicmarket_auctions","constraint":"atomicmarket_auctions_maker_marketplace_fkey","file":"ri_triggers.c","line":"2465","routine":"ri_ReportViolation"}}
eosio-contract-api-filler      | 2022-05-20T04:51:23.853Z [PID:39] [error] : Error occurred while executing block range from #109316981 to 109316990 
eosio-contract-api-postgres    | 2022-05-20 04:51:23.854 UTC [35] WARNING:  there is no transaction in progress
eosio-contract-api-filler      | 2022-05-20T04:51:23.855Z [PID:39] [error] : Consumer queue stopped due to an error at #109316990 Release called on client which has already been released to the pool. {"stack":"Error: Release called on client which has already been released to the pool.\n    at throwOnDoubleRelease (/home/application/app/node_modules/pg-pool/index.js:27:9)\n    at Client.release (/home/application/app/node_modules/pg-pool/index.js:296:9)\n    at ContractDBTransaction.abort (/home/application/app/build/filler/database.js:485:25)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async StateReceiver.process (/home/application/app/build/filler/receiver.js:175:17)\n    at async /home/application/app/build/filler/receiver.js:90:17\n    at async run (/home/application/app/node_modules/p-queue/dist/index.js:163:29)"}
eosio-contract-api-filler      | 2022-05-20T04:51:30.769Z [PID:39] [warn] : Reader atomic-1 - No blocks processed [DS:0|SH:40|JQ:0] - Stopping in 3590 seconds 
```
Any ideas?

**Comment by fabian-emilius** [comment]
Yes need to start syncing at the block where atomicassets was deployed
